trigger:
- master

name: Deploy Bicep files

variables:
  azureServiceConnection: 'azureServiceConnection'
  resourceGroupName: 'reversefunctionrg'
  location: 'australiasoutheast'
  templateFile: 'main.bicep'
pool: 'My Devices'

steps:
- task: AzureCLI@2
  inputs:
    azureSubscription: $(azureServiceConnection)
    scriptType: ps
    scriptLocation: inlineScript
    inlineScript: |
      az --version
      az group create --name $(resourceGroupName) --location $(location)
      az deployment group create --resource-group $(resourceGroupName) --template-file $(templateFile)